name: "Release"
# SECRETS NEEDED:
# DOCKER_USERNAME - Container Registry Username (github or dockerhub)
# DOCKER_ACCESS_TOKEN - Container registry Personal access token with push priveledges
# CM_API_KEY - ChartMuseum API Key with permission to push
# CM_REPO_URL - ChartMusuem REPO URL in the format: 'https://h.cfcr.io/bsord/charts'

on:
  push:
    branches:
      - "master"
      - "develop"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: Bump version and push tag
        id: bump-tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: "master,main"
          DEFAULT_BUMP: "patch"
          INITIAL_VERSION: "1.0.0"

      - name: Update version in version files
        id: update-version
        run: |
          # Update package.json
          npm version ${{ steps.bump-tag.outputs.new_tag }} --no-git-tag-version
          # Update Helm chart version
          sed -r -i "s/(version:[^*]|appVersion:[^*])([[:alnum:].]*.*)/\1${{ steps.bump-tag.outputs.new_tag }}/g" ./chart/Chart.yaml

      - name: Build and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          tags: "${{ steps.bump-tag.outputs.new_tag }}"

      - name: Push chart to bsord/helm-charts
        run: |
          CLONE_DIR=$(mktemp -d)
          git clone "https://${{ secrets.GITHUB_TOKEN }}@github.com/bsord/helm-charts.git" "$CLONE_DIR"
          mkdir -p $CLONE_DIR/sources/tiles-client/
          cp chart/. "$CLONE_DIR/sources/tiles-client/"
          cd "$CLONE_DIR"
          git add .
          git commit --message "Update from https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
          git push -u origin master

      - name: Push Helm chart
        uses: bsord/helm-push@v4
        with:
          access-token: ${{ secrets.CM_API_KEY }}
          registry-url: ${{ secrets.CM_REPO_URL }} 
          force: true
          chart-folder: chart
      
